### ISSUE TITLE
System.InvalidOperationException: The artefact vertex has no producer vertex set. Set the ProduceBy before retrieving its value

### ISSUE THREAD

**Issue by dgrechka** [itislab/alpheus#102]
on Ubuntu:

```
(venv) dmitry@compute:~/repos/PANDA-Challenge/experiments/dgrechka$ alpheus compute 13c/trainLearningCurves.png
System.InvalidOperationException: The artefact vertex has no producer vertex set. Set the ProduceBy before retrieving its value
   at ItisLab.Alpheus.DependencyGraph.ArtefactVertex.get_ProducedBy() in C:\repos\alpheus\AlpheusCore\DependencyGraph.fs:line 136
   at ItisLab.Alpheus.DependencyGraphToAngaraWrapper.ItisLab-Alpheus-AngaraTranslator-IDependencyGraph`2-ProducedBy(ArtefactVertex artefact) in C:\repos\alpheus\AlpheusCore\DependencyGraphToAngaraWrapper.fs:line 19
   at ItisLab.Alpheus.AngaraTranslator.registerArtefactRelatedMethods@34.Invoke(Artefact artefact, FlowGraph`1 graph, FSharpMap`2 methodNodeMap) in C:\repos\alpheus\AlpheusCore\AngaraTranslator.fs:line 34
   at ItisLab.Alpheus.AngaraTranslator.registerArtefact@61.Invoke(Tuple`2 tupledArg, Artefact artefact) in C:\repos\alpheus\AlpheusCore\AngaraTranslator.fs:line 61
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 729
   at ItisLab.Alpheus.AngaraTranslator.translate[Node,Artefact,Method](FSharpFunc`2 nodeFactory, IDependencyGraph`2 dependencyGraph) in C:\repos\alpheus\AlpheusCore\AngaraTranslator.fs:line 63
   at ItisLab.Alpheus.ComputationGraph.buildGraph(String experimentRoot, Graph g, FSharpFunc`2 checkStoragePresence, FSharpFunc`2 restoreFromStorage) in C:\repos\alpheus\AlpheusCore\ComputationGraph.fs:line 292
   at ItisLab.Alpheus.API.compute@341-1.Invoke(Graph _arg1) in C:\repos\alpheus\AlpheusCore\API.fs:line 363
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 417
   at ItisLab.Alpheus.API.buildDependencyGraphAsync@22-3.Invoke(AsyncActivation`1 ctxt) in C:\repos\alpheus\AlpheusCore\API.fs:line 22
   at ItisLab.Alpheus.API.compute@339-3.Invoke(AsyncActivation`1 ctxt) in C:\repos\alpheus\AlpheusCore\API.fs:line 339
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 349
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 870
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 890
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 1153
   at ItisLab.Alpheus.API.compute(String experimentRoot, ArtefactId artefactId) in C:\repos\alpheus\AlpheusCore\API.fs:line 338
   at ItisLab.Alpheus.CliRunner.run@66-25.Invoke(Tuple`2 _arg8) in C:\repos\alpheus\Alpheus.CLI\Runner.fs:line 66
   at ItisLab.Alpheus.Results.ResultBuilder.Bind[a2,a3,a4](FSharpResult`2 m, FSharpFunc`2 f) in C:\repos\alpheus\AlpheusCore\ResultBuilder.fs:line 16
   at ItisLab.Alpheus.CliRunner.run@63-24.Invoke(Unit unitVar) in C:\repos\alpheus\Alpheus.CLI\Runner.fs:line 65
   at ItisLab.Alpheus.Results.ResultBuilder.Run[m](FSharpFunc`2 f) in C:\repos\alpheus\AlpheusCore\ResultBuilder.fs:line 31
   at ItisLab.Alpheus.CliRunner.run(String programName, String workingDir, ParseResults`1 parseResults) in C:\repos\alpheus\Alpheus.CLI\Runner.fs:line 62
   at ItisLab.Alpheus.Program.main(String[] argv) in C:\repos\alpheus\Alpheus.CLI\Program.fs:line 42
```

**Comment by dgrechka** [comment]
Issue happens when the alph file contains windows generated paths with backslashes, and the alph file is executed on linux.

Replacing `\\` with `/` is workaround.
