### ISSUE TITLE
Vector operation 3 not equal 2

### ISSUE THREAD

**Issue by dgrechka** [itislab/alpheus#41]
See https://travis-ci.org/itislab/alpheus/builds/585648447?utm_source=github_status&utm_medium=notification

```
Microsoft.NETCore.App]

[xUnit.net 00:00:03.13]     ItisLab.Alpheus.Tests.Vector scenarios through API.Runs same method for multiple input files [FAIL]

Test run in progress.archiver: Archive content to extract to disk

archiver: __artefact__:__artefact__

/home/travis/build/itislab/alpheus/AlpheusUnitTests/bin/Debug/netcoreapp2.1/data/singleTimeDirs/ef5b4cbb-d726-4b9c-98f0-48b1097ee44c/dir1/test1.txt single file artefact restored

archiver: Archive content to extract to disk

archiver: __artefact__:__artefact__

archiver: Archive content to extract to disk

archiver: __artefact__:__artefact__

/home/travis/build/itislab/alpheus/AlpheusUnitTests/bin/Debug/netcoreapp2.1/data/singleTimeDirs/265970d6-b786-4f3a-a370-1114fe2f2a27/1_2.txt single file artefact restored

/home/travis/build/itislab/alpheus/AlpheusUnitTests/bin/Debug/netcoreapp2.1/data/singleTimeDirs/265970d6-b786-4f3a-a370-1114fe2f2a27/3.txt single file artefact restored

  X ItisLab.Alpheus.Tests.Vector scenarios through API.Runs same method for multiple input files [673ms]

  Error Message:

   Assert.Equal() Failure

Expected: 3

Actual:   2

  Stack Trace:

     at <StartupCode$AlpheusUnitTests>.$ApiTests.Vectors.Runs same method for multiple input files@67-6.Invoke(Unit _arg7) in /home/travis/build/itislab/alpheus/AlpheusUnitTests/ApiTests.Vectors.fs:line 72

   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)

   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@607.Invoke(AsyncActivation`1 ctxt)

   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)

--- End of stack trace from previous location where exception was thrown ---

--- End of stack trace from previous location where exception was thrown ---
```

**Comment by dvoits** [comment]
Again reproduced in the special test: https://travis-ci.org/itislab/alpheus/builds/587096471?utm_source=github_status&utm_medium=notification

**Comment by dvoits** [comment]
https://travis-ci.org/itislab/alpheus/builds/587449909?utm_source=github_status&utm_medium=notification
