### ISSUE TITLE
NullReferenceException in 'angara compute'

### ISSUE THREAD

**Issue by sergey-berezin** [itislab/alpheus#48]
I have following exception:

```Internal error occurred: Failed to compute the artefacts:
        System.NullReferenceException: Object reference not set to an instance of an object.
   at ItisLab.Alpheus.ComputationGraph.hashesToRestore@113.Invoke(FSharpOption`1 x) in D:\alpheus\AlpheusCore\ComputationGraph.fs:line 113
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map2@102.DoMoveNext(c& curr)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at ItisLab.Alpheus.ComputationGraph.Execute@112-21.Invoke(FSharpOption`1[] _arg4) in D:\alpheus\AlpheusCore\ComputationGraph.fs:line 115
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit()
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at ItisLab.Alpheus.ComputationGraph.CommandMethod.Execute(FSharpList`1 inputs, FSharpOption`1 _arg1) in D:\alpheus\AlpheusCore\ComputationGraph.fs:line 56
   at Angara.Execution.Runtime`1.buildEvaluation(m v, FSharpList`1 index, UInt64 time, State`2 state, CancellationTokenSource cts, Boolean doContinue, Unit unitVar0)
```

when running `alpheus compute irisdata.png` command in attached project folder.

[repro.zip](https://github.com/itislab/alpheus/files/3635841/repro.zip)

**Comment by sergey-berezin** [comment]
Update. After 581f4fe behaviour changed, but still incorrect.

```
API: Building the dependency graph
API: Dependency graph is built (4 artefacts; 4 methods)
API: Running computations
Execution: iris.csv[]: Started
DependencyGraph: Calculating hash of D:\iris-tutorial\download.py...
Hash: Artefact D:\iris-tutorial\download.py - acquiring data hash...
Hash: Artefact D:\iris-tutorial\download.py hash is extracted from up-to-date .hash file
DependencyGraph: Calculating hash of D:\iris-tutorial\iris.csv...
Hash: Artefact D:\iris-tutorial\iris.csv - acquiring data hash...
Hash: Artefact D:\iris-tutorial\iris.csv hash is calculated (didn't find precomputed .hash file)
Execution: iris.csv[]: skipping as up to date
Execution: irisdata.png[]: Started
Execution: irisdata.png: Needs recomputation as disk version of the input does not match expected version
Execution: [                            irisdata.png]:  Running "python plot.py" in "D:\iris-tutorial\"
Execution: [                            irisdata.png]:  Started subprocess (PID=16668)
ExecutionOutput: [                   irisdata.png [stderr]]:    Traceback (most recent call last):
ExecutionOutput: [                   irisdata.png [stderr]]:      File "plot.py", line 6, in <module>
ExecutionOutput: [                   irisdata.png [stderr]]:        dataset = pandas.read_csv('iris.csv')
ExecutionOutput: [                   irisdata.png [stderr]]:      File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
ExecutionOutput: [                   irisdata.png [stderr]]:        return _read(filepath_or_buffer, kwds)
ExecutionOutput: [                   irisdata.png [stderr]]:      File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 440, in _read
ExecutionOutput: [                   irisdata.png [stderr]]:        parser = TextFileReader(filepath_or_buffer, **kwds)
ExecutionOutput: [                   irisdata.png [stderr]]:      File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
ExecutionOutput: [                   irisdata.png [stderr]]:        self._make_engine(self.engine)
ExecutionOutput: [                   irisdata.png [stderr]]:      File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
ExecutionOutput: [                   irisdata.png [stderr]]:        self._engine = CParserWrapper(self.f, **self.options)
ExecutionOutput: [                   irisdata.png [stderr]]:      File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
ExecutionOutput: [                   irisdata.png [stderr]]:        self._reader = parsers.TextReader(src, **kwds)
ExecutionOutput: [                   irisdata.png [stderr]]:      File "pandas\_libs\parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
ExecutionOutput: [                   irisdata.png [stderr]]:      File "pandas\_libs\parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
ExecutionOutput: [                   irisdata.png [stderr]]:    FileNotFoundError: File b'iris.csv' does not exist
Execution: [                            irisdata.png]:  Subprocess (PID=16668) exited with exit code 1
Internal error occurred: Failed to compute the artefacts:
        System.InvalidOperationException: Process exited with non-successful exit code 1
   at ItisLab.Alpheus.ComputationGraph.Execute@127-25.Invoke(Unit unitVar) in D:\alpheus\AlpheusCore\ComputationGraph.fs:line 135
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@607.Invoke(AsyncActivation`1 ctxt)
   at ItisLab.Alpheus.ComputationGraph.Execute@120-31.Invoke(AsyncActivation`1 ctxt) in D:\alpheus\AlpheusCore\ComputationGraph.fs:line 120
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit()
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at ItisLab.Alpheus.ComputationGraph.CommandMethod.Execute(FSharpList`1 inputs, FSharpOption`1 _arg1) in D:\alpheus\AlpheusCore\ComputationGraph.fs:line 59
   at Angara.Execution.Runtime`1.buildEvaluation(m v, FSharpList`1 index, UInt64 time, State`2 state, CancellationTokenSource cts, Boolean doContinue, Unit unitVar0)
```
Possible cause:
1. `alpheus build -d some-artefact -o another-artefact ...`
2. delete `some-artefact` from disk
3. `alpheus compute another-artefact`
