### ISSUE TITLE
Failed test: ItisLab.Alpheus.Tests.Vector scenarios.Scatter: Creates many files and the processes them as a vector [106ms]

### ISSUE THREAD

**Issue by dvoits** [itislab/alpheus#50]
See https://travis-ci.org/itislab/alpheus/builds/587396043?utm_source=github_status&utm_medium=notification

Test run in progress.  X ItisLab.Alpheus.Tests.Vector scenarios.Scatter: Creates many files and the processes them as a vector [106ms]
  Error Message:
   Expected successful operation, but got error: SystemError
  "Failed to compute the artefacts: 
	Newtonsoft.Json.JsonWriterException: Token PropertyName in state Property would result in an invalid JSON object. Path 'Origin.Fields[0].Outputs[0].Hash'.
   at Newtonsoft.Json.JsonWriter.AutoComplete(JsonToken tokenBeingWritten)
   at Newtonsoft.Json.JsonTextWriter.WritePropertyName(String name)
   at ItisLab.Alpheus.CustomSerializers.writeValue@22-1.Invoke(Tuple`2 tupledArg) in /home/travis/build/itislab/alpheus/AlpheusCore/CustomSerializers.fs:line 24
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at ItisLab.Alpheus.CustomSerializers.writeValue@14.Invoke(Tuple`2 tupledArg, MdMap`2 value) in /home/travis/build/itislab/alpheus/AlpheusCore/CustomSerializers.fs:line 20
   at ItisLab.Alpheus.CustomSerializers.ArtefactVersionConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer) in /home/travis/build/itislab/alpheus/AlpheusCore/CustomSerializers.fs:line 28
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.Converters.DiscriminatedUnionConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at ItisLab.Alpheus.AlphFiles.save(AlphFile alphfile, String filepath) in /home/travis/build/itislab/alpheus/AlpheusCore/AlphFiles.fs:line 55
   at ItisLab.Alpheus.DependencyGraph.SaveAlphFile@194.Invoke(Unit unitVar0) in /home/travis/build/itislab/alpheus/AlpheusCore/DependencyGraph.fs:line 197
   at ItisLab.Alpheus.DependencyGraph.ArtefactVertex.SaveAlphFile() in /home/travis/build/itislab/alpheus/AlpheusCore/DependencyGraph.fs:line 194
   at ItisLab.Alpheus.DependencyGraph.OnSucceeded@382-6.Invoke(LinkToArtefact out) in /home/travis/build/itislab/alpheus/AlpheusCore/DependencyGraph.fs:line 382
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at ItisLab.Alpheus.DependencyGraph.OnSucceeded@381-3.Invoke(Unit _arg5) in /home/travis/build/itislab/alpheus/AlpheusCore/DependencyGraph.fs:line 382
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@607.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit()
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation)
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at ItisLab.Alpheus.ComputationGraph.CommandMethod.Execute(FSharpList`1 inputs, FSharpOption`1 _arg1) in /home/travis/build/itislab/alpheus/AlpheusCore/ComputationGraph.fs:line 59
   at Angara.Execution.Runtime`1.buildEvaluation(m v, FSharpList`1 index, UInt64 time, State`2 state, CancellationTokenSource cts, Boolean doContinue, Unit unitVar0)"
Expected: True
Actual:   False
  Stack Trace:
     at ItisLab.Alpheus.Tests.Utils.assertResultOk[a,b](FSharpResult`2 result) in /home/travis/build/itislab/alpheus/AlpheusUnitTests/TestUtils.fs:line 95
   at <StartupCode$AlpheusUnitTests>.$ApiTests.Vectors.Scatter: Creates many files and the processes them as a vector@133-1.Invoke(FSharpResult`2 _arg7) in /home/travis/build/itislab/alpheus/AlpheusUnitTests/ApiTests.Vectors.fs:line 136
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at Microsoft.FSharp.Control.AsyncPrimitives.Bind@495-1.Invoke(TResult result1)
   at Microsoft.FSharp.Control.AsyncActivation`1.OnSuccess(T result)
   at ItisLab.Alpheus.API.buildAsync@382-6.Invoke(AsyncActivation`1 ctxt) in /home/travis/build/itislab/alpheus/AlpheusCore/API.fs:line 382
   at Microsoft.FSharp.Control.AsyncPrimitives.unitAsync@607.Invoke(AsyncActivation`1 ctxt)
   at ItisLab.Alpheus.API.buildAsync@377-8.Invoke(AsyncActivation`1 ctxt) in /home/travis/build/itislab/alpheus/AlpheusCore/API.fs:line 377
   at ItisLab.Alpheus.DependencyGraph.AddMethod@462-4.Invoke(AsyncActivation`1 ctxt) in /home/travis/build/itislab/alpheus/AlpheusCore/DependencyGraph.fs:line 462
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at <StartupCode$FSharp-Core>.$Async.Return@1097.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location where exception was thrown ---
--- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
 Creating unique test dir data/singleTimeDirs/35c1f4d5-e508-474a-a9fe-60b16c3ac0ea/
 API: Outputs: [Path "1_2.txt"]
 API: Dependencies: []
 API: Outputs: [Path "samples/*.txt"]
 API: Command: "/bin/sh -c "for i in $(seq 1 3); do echo sample$i > sample$i.txt; done""
 API: Building the dependency graph
 API: Dependency graph is built (0 artefacts; 0 methods)
 DependencyGraph: Saving alph file for artefact Path "samples/*.txt"
 DependencyGraph: Saved alph file for artefact Path "samples/*.txt"
 API: Command: "/bin/sh -c "cat $in1 > $out1; cat $in2 >> $out1""
 API: Building the dependency graph
 API: Dependency graph is built (2 artefacts; 2 methods)
 API: Dependency graph is built (1 artefacts; 1 methods)
 DependencyGraph: Saving alph file for artefact Path "1_2.txt"
 API: Graph artefacts: [Artefact(samples/*.txt|)]
 DependencyGraph: Saved alph file for artefact Path "1_2.txt"
 API: Dependency graph is built (3 artefacts; 3 methods)
 API: Building the dependency graph
 API: Graph artefacts: [Artefact(1.txt|); Artefact(2.txt|); Artefact(1_2.txt|)]
 API: Dependency graph is built (1 artefacts; 1 methods)
 API: Running computations
 API: Dependencies: [Path "1_2.txt"; Path "3.txt"]
 API: Outputs: [Path "1_2_3.txt"]
 API: Command: "/bin/sh -c "cat $in1 > $out1; cat $in2 >> $out1""
 API: Building the dependency graph
 API: Dependency graph is built (4 artefacts; 4 methods)
 DependencyGraph: Saving alph file for artefact Path "1_2_3.txt"
 DependencyGraph: Saved alph file for artefact Path "1_2_3.txt"
 API: Dependency graph is built (5 artefacts; 5 methods)
 API: Graph artefacts: [Artefact(1.txt|); Artefact(2.txt|); Artefact(3.txt|); Artefact(1_2.txt|);
  Artefact(1_2_3.txt|)]
 API: Dependencies: [Path "dir1/"]
 Execution: samples/*.txt[]: Started
 API: Outputs: [Path "dir1_copy/"]
 Execution: samples/*.txt: Needs recomputation as disk version of the output does not match expected version
 API: Command: "/bin/sh -c "rm -Rv $out1 ; cp -Rv $in1 $out1""
 API: Building the dependency graph
 Execution: [                           samples/*.txt]:	Running "/bin/sh -c "for i in $(seq 1 3); do echo sample$i > sample$i.txt; done"" in "/home/travis/build/itislab/alpheus/AlpheusUnitTests/bin/Debug/netcoreapp2.1/data/singleTimeDirs/971b3d66-5ad8-4c64-a04a-e191d2726470/data/singleTimeDirs/35c1f4d5-e508-474a-a9fe-60b16c3ac0ea/samples/"
 API: Dependency graph is built (1 artefacts; 1 methods)
 DependencyGraph: Saving alph file for artefact Path "dir1_copy/"
 DependencyGraph: Saved alph file for artefact Path "dir1_copy/"
 API: Dependency graph is built (2 artefacts; 2 methods)
 API: Graph artefacts: [Artefact(dir1/|); Artefact(dir1_copy/|)]
 Execution: [                           samples/*.txt]:	Started subprocess (PID=5025)
 Execution: [                           samples/*.txt]:	Subprocess (PID=5025) exited with exit code 0
 Execution: samples/*.txt[]: Method succeeded
 Execution: samples/*.txt[]: Program succeeded. Calculating hashes of the outputs...
 DependencyGraph: Method "samples/*.txt"[[]] succeeded
 DependencyGraph: Calculating hash of /home/travis/build/itislab/alpheus/AlpheusUnitTests/bin/Debug/netcoreapp2.1/data/singleTimeDirs/971b3d66-5ad8-4c64-a04a-e191d2726470/data/singleTimeDirs/35c1f4d5-e508-474a-a9fe-60b16c3ac0ea/samples/sample2.txt...
 DependencyGraph: Calculating hash of /home/travis/build/itislab/alpheus/AlpheusUnitTests/bin/Debug/netcoreapp2.1/data/singleTimeDirs/971b3d66-5ad8-4c64-a04a-e191d2726470/data/singleTimeDirs/35c1f4d5-e508-474a-a9fe-60b16c3ac0ea/samples/sample3.txt...
 Hash: Artefact /home/travis/build/itislab/alpheus/AlpheusUnitTests/bin/Debug/netcoreapp2.1/data/singleTimeDirs/971b3d66-5ad8-4c64-a04a-e191d2726470/data/singleTimeDirs/35c1f4d5-e508-474a-a9fe-60b16c3ac0ea/samples/sample3.txt - acquiring data hash...
 Hash: Artefact /home/travis/build/itislab/alpheus/AlpheusUnitTests/bin/Debug/netcoreapp2.1/data/singleTimeDirs/971b3d66-5ad8-4c64-a04a-e191d2726470/data/singleTimeDirs/35c1f4d5-e508-474a-a9fe-60b16c3ac0ea/samples/sample2.txt - acquiring data hash...
 DependencyGraph: Calculating hash of /home/travis/build/itislab/alpheus/AlpheusUnitTests/bin/Debug/netcoreapp2.1/data/singleTimeDirs/971b3d66-5ad8-4c64-a04a-e191d2726470/data/singleTimeDirs/35c1f4d5-e508-474a-a9fe-60b16c3ac0ea/samples/sample1.txt...
 Hash: Artefact /home/travis/build/itislab/alpheus/AlpheusUnitTests/bin/Debug/netcoreapp2.1/data/singleTimeDirs/971b3d66-5ad8-4c64-a04a-e191d2726470/data/singleTimeDirs/35c1f4d5-e508-474a-a9fe-60b16c3ac0ea/samples/sample1.txt - acquiring data hash...
 Hash: Artefact /home/travis/build/itislab/alpheus/AlpheusUnitTests/bin/Debug/netcoreapp2.1/data/singleTimeDirs/971b3d66-5ad8-4c64-a04a-e191d2726470/data/singleTimeDirs/35c1f4d5-e508-474a-a9fe-60b16c3ac0ea/samples/sample1.txt hash is calculated (didn't find precomputed .hash file)
 Successfully deleted unique test dir data/singleTimeDirs/35c1f4d5-e508-474a-a9fe-60b16c3ac0ea/

**Comment by dgrechka** [comment]
Seems to be resolved. Does not reproduce anymore
