### ISSUE TITLE
"ItisLab.Alpheus.Tests.Vector scenarios.Scatter-scatter-vector-reduce-reduce" test failure

### ISSUE THREAD

**Issue by dgrechka** [itislab/alpheus#67]
See https://travis-ci.org/itislab/alpheus/builds/640586896?utm_source=github_status&utm_medium=notification

**Comment by dgrechka** [comment]
```System.ArgumentException: Rank of artefact is 2 while index length is 1

Parameter name: index

   at ItisLab.Alpheus.ActualArtefactVersion.checkRank(FSharpList`1 index) in /home/travis/build/itislab/alpheus/AlpheusCore/ActualVersion.fs:line 18

   at ItisLab.Alpheus.ActualArtefactVersion.Get(FSharpList`1 index) in /home/travis/build/itislab/alpheus/AlpheusCore/ActualVersion.fs:line 43

   at ItisLab.Alpheus.AngaraGraphCommon.checkIdx@176-1.Invoke(Unit unitVar) in /home/travis/build/itislab/alpheus/AlpheusCore/AngaraGraphCommon.fs:line 176

   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)

   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.FSharp.Control.AsyncResult`1.Commit()

   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation)

   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout)

   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)

   at ItisLab.Alpheus.ComputationGraph.CommandMethod.Execute(FSharpList`1 inputs, FSharpOption`1 _arg1) in /home/travis/build/itislab/alpheus/AlpheusCore/ComputationGraph.fs:line 71

   at Angara.Execution.Runtime`1.buildEvaluation(m v, FSharpList`1 index, UInt64 time, State`2 state, CancellationTokenSource cts, Boolean doContinue, Unit unitVar0)"

Expected: True

Actual:   False```
