### ISSUE TITLE
Composite extensions are not supported (e.g. *.tar.gz)

### ISSUE THREAD

**Issue by dgrechka** [itislab/alpheus#73]
Expected User error, as script did not produce the output files (scatter method)
Got
```Internal error occurred: Failed to compute the artefacts:
        Newtonsoft.Json.JsonWriterException: Token PropertyName in state Property would result in an invalid JSON object. Path 'Origin.Fields[0].Outputs[0].Hash'.
   at Newtonsoft.Json.JsonWriter.AutoComplete(JsonToken tokenBeingWritten)
   at Newtonsoft.Json.JsonTextWriter.WritePropertyName(String name)
   at ItisLab.Alpheus.CustomSerializers.writeValue@22-1.Invoke(Tuple`2 tupledArg) in C:\repos\alpheus\AlpheusCore\CustomSerializers.fs:line 24
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source) in E:\A\_work\130\s\src\fsharp\FSharp.Core\seq.fs:line 495
   at ItisLab.Alpheus.CustomSerializers.writeValue@13(JsonWriter tupledArg0, JsonSerializer tupledArg1, MdMap`2 value) in C:\repos\alpheus\AlpheusCore\CustomSerializers.fs:line 25
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)```

**Comment by dgrechka** [comment]
Initial vertex build command:
```
(venv-gpu) C:\ML\bengaliai-cv19\data>alpheus build -d ..\packages\FSharp.Compiler.Tools\tools\fsiAnyCpu.exe -d ..\code\scripts\GenerateCVSplits.fsx -d bengaliai-cv19\ -o .\5foldCvSplits\*.val_ids.csv -o .\5foldCvSplits\*.root_stats.csv -o .\5foldCvSplits\*.vowel_stats.csv -o .\5foldCvSplits\*.consonant_stats.csv "$in1 $in2 $in3\train.csv $out1 $out2 $out3 $out4 5"
```
