### ISSUE TITLE
exception during load vector alph file

### ISSUE THREAD

**Issue by dgrechka** [itislab/alpheus#77]
vector element [4] exists
other vector elements are absent

got error
```
(venv-gpu) C:\ML\bengaliai-cv19>alpheus compute experiment_outputs\dgrechka_1_mobileNetV2_bottleneck\vector.alph
Internal error occurred (please report it at https://github.com/itislab/alpheus/issues): Failed to compute the artefacts:
        System.ArgumentException: Rank of artefact is 1 while index length is 0
Parameter name: index
   at ItisLab.Alpheus.ActualArtefactVersion.checkRank(FSharpList`1 index) in C:\repos\alpheus\AlpheusCore\ActualVersion.fs:line 18
   at ItisLab.Alpheus.ActualArtefactVersion.Get(FSharpList`1 index) in C:\repos\alpheus\AlpheusCore\ActualVersion.fs:line 43
   at ItisLab.Alpheus.AngaraGraphCommon.getActualForExpected@119-4.Invoke(Unit unitVar) in C:\repos\alpheus\AlpheusCore\AngaraGraphCommon.fs:line 119
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncResult`1.Commit() in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 349
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronouslyInCurrentThread[a](CancellationToken cancellationToken, FSharpAsync`1 computation) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 870
   at Microsoft.FSharp.Control.AsyncPrimitives.RunSynchronously[T](CancellationToken cancellationToken, FSharpAsync`1 computation, FSharpOption`1 timeout) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 890
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 1151
   at Angara.Execution.Runtime`1.buildEvaluation(m v, FSharpList`1 index, UInt64 time, State`2 state, CancellationTokenSource cts, Boolean doContinue, Unit unitVar0)
```

Vertex command:
```
(venv-gpu) C:\ML\bengaliai-cv19>alpheus -v verbose build -rg gpu -d code\dgrechka\train_mobileNetV2_bottleneck.py -d data\bengaliai-cv19\ -d data\5foldCvSplits\*.val_ids.csv -o experiment_outputs\dgrechka_1_mobileNetV2_bottleneck\*\ "python $in1 $in2 $in3 $out1"
```

**Comment by dgrechka** [comment]
Deleting artefact data does not help. Same exception.

Alph file:
```
{
  "FileFormatVersion": 1,
  "Origin": {
    "Case": "CommandOrigin",
    "Fields": [
      {
        "Inputs": [
          {
            "RelativePath": "..\\..\\code\\dgrechka\\train_mobileNetV2_bottleneck.py",
            "Hash": "13807DFC426019E309E01CE6B5D14E5322190C882A9E33C9353DE56EFB999FBC55879EFB50E4555E30494EEA3D0C37860AEFB0CAF9DF634D317217F63E5B5C30"
          },
          {
            "RelativePath": "..\\..\\data\\bengaliai-cv19\\",
            "Hash": "D09946D9348B9135927E3C69F22AFB441F5EA040995229E4119F6B3B6DC10537DE1BF1FA6850A5BCFA1C90849BDA14AEC20B69EC410422F558CDA8CBE0A5362F"
          },
          {
            "RelativePath": "..\\..\\data\\5foldCvSplits\\*.val_ids.csv",
            "Hash": {
              "4": "126EC1D9569D45674A0EB7F9CB1A861F8CBFA854CEBA03061EFE070F004C151F8BFDD72980139891A828E1D03B99BFDE36DBAF0C46F149F7106C0DA04AD20F8F"
            }
          }
        ],
        "Outputs": [
          {
            "RelativePath": "*\\",
            "Hash": {
              "4": "5FBB40BCCAA076244B558CC6BA30D2907DBA7D4B92093CDA45B14EF89B98A191FEFAA85AD5704A6F1CCC762CD89135F17A68BAE086FC53B67785197D47B34225"
            }
          }
        ],
        "ResourceGroups": [
          "gpu"
        ],
        "SuccessfulExitCodes": [
          0
        ],
        "OutputIndex": 0,
        "WorkingDirectory": "..\\..",
        "Command": "python $in1 $in2 $in3 $out1",
        "Signature": "F6CAA8BF1432F2612D8F606B1A3636E90D52E58D",
        "OutputsCleanDisabled": false
      }
    ]
  },
  "IsTracked": false
}
```

**Comment by dgrechka** [comment]
Setting `hash` of outputs to `null` instead of dictionary in alph file eliminates the exception. Thus problem is with `hash` value
